code/sjhy/WebApp/Areas/Manager/Controllers/RolesManagerController.cs
global using Commons.Pages;
global using IServices;
global using X.PagedList;
using Microsoft.AspNetCore.Mvc;
using Entity.ViewModels.Roles;

namespace WebApp.Areas.Manager.Controllers
{
    [Area("Manager")]
    public class RolesManagerController : Controller
    {
        private IRolesService _rolesSvc;
        public RolesManagerController(IRolesService rolesSvc)
        {
            _rolesSvc = rolesSvc;
        }

        [HttpGet]
        public async Task<IActionResult> List(string? search,int page = 1)
        {
            search = search ?? string.Empty;
            var data = await _rolesSvc.GetRolesByTitleAsync(search);
            var list = data.Select(r => new RolesListViewModel 
            {
                RolesId = r.Id,
                RolesTitle = r.Title,
                UpdateTime = r.UpdateTime
            }).ToList();

            IPagedList<RolesListViewModel> pages = list.ToPagedList(page, PageConfig.PageSize);
            ViewBag.Search = search;
            return View(pages);
        }


        [HttpGet]
        public IActionResult Add() 
        {
            return View(new RolesAddViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Add(RolesAddViewModel model) 
        {
            if (ModelState.IsValid) 
            {
                //如果能够进入到这个if就代表通过验证了
               var res = await 
                    _rolesSvc.AddRolesAsync(model.RolesTitle);

                if (res > 0)
                    return Redirect("../../../Manager/RolesManager/List");
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var data = await _rolesSvc.GetRolesByIdAsync(id);
            if(data == null || string.IsNullOrEmpty(data.Title))
                return Redirect("../../../Manager/RolesManager/List");
            return View(new RolesEditViewModel 
            {
                RolesId = data.Id,
                RolesTitle = data.Title
            });
        }

        [HttpPost]
        public async Task<IActionResult> Edit(RolesEditViewModel model) 
        {
            if (ModelState.IsValid) 
            {
                var res = await _rolesSvc.EditRolesAsync(model.RolesId, model.RolesTitle);
                if(res > 0)
                    return Redirect("../../../Manager/RolesManager/List");
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id) 
        {
            var res = await _rolesSvc.DeleteRolesAsync(id);
            return Json(res > 0);
        }   





    }
}

code/sjhy/WebApp/Areas/Manager/Views/RolesManager/Add.cshtml
@model Entity.ViewModels.Roles.RolesAddViewModel
@{
    ViewBag.Title = "新增身份信息";
}
<div class="panel panel-headline">
    <div class="panel-heading">
        <h3 class="panel-title">新增身份信息</h3>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <form asp-action="Add" asp-controller="RolesManager" asp-area="Manager"  method="post">
                    <div class="form-group">
                        <label for="">身份名称</label>
                        <input asp-for="RolesTitle" class="form-control" />
                        <span asp-validation-for="RolesTitle" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <button class="btn btn-primary">保存</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>    

code/sjhy/WebApp/Areas/Manager/Views/RolesManager/Edit.cshtml
@model Entity.ViewModels.Roles.RolesEditViewModel
@{
    ViewBag.Title = "编辑身份信息";
}

<div class="panel panel-headline">
    <div class="panel-heading">
        <h3 class="panel-title">编辑身份信息</h3>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <form asp-action="Edit" asp-controller="RolesManager" asp-area="Manager"  method="post">
                    <div class="form-group">
                        <label for="">身份编号</label>
                        <input asp-for="RolesId" readonly class="form-control" />
                    </div>
                    <div class="form-group">
                        <label for="">身份名称</label>
                        <input asp-for="RolesTitle" class="form-control" />
                        <span asp-validation-for="RolesTitle" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <button class="btn btn-primary">保存</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>   

code/sjhy/WebApp/Areas/Manager/Views/RolesManager/List.cshtml
@model IPagedList<Entity.ViewModels.Roles.RolesListViewModel>
@{
    ViewBag.Title = "身份管理界面";
}

<div class="panel panel-headline">
    <div class="panel-heading">
        <h3 class="panel-title">身份管理界面</h3>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-5 col-md-offset-1">
                <form asp-action="List" asp-controller="RolesManager" asp-area="Manager" method="get">
                     <div class="input-group">
                          <input class="form-control" name="search" type="text" value="@ViewBag.Search">
                          <span class="input-group-btn">
                              <button type="submit" class="btn btn-primary" type="button">
                                  <i class="fa fa-search"></i> 搜索</button>
                                  <!-- font-awesome  -->
                          </span>
                     </div>
                </form>
            </div>
            <div class="col-md-3">
                <a asp-action="Add" asp-controller="RolesManager" asp-area="Manager" class="btn btn-success">
                    <i class="fa fa-plus"></i> 新增身份信息
                </a>

            </div>

        </div>
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>序号</th>
                            <th>身份名称</th>
                            <th>修改时间</th>
                            <th>操作</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.RolesId</td>
                                <td>@item.RolesTitle</td>
                                <td>@item.UpdateTime</td>
                                <td>
                                    <a asp-action="Edit" asp-controller="RolesManager" asp-area="Manager" asp-route-id="@item.RolesId" class="btn btn-warning">
                                         <i class="fa fa-pencil"></i>   修改
                                    </a>
                                    <a href="javascript:void(0);" onclick="DeleteInfo(@item.RolesId,'../../../Manager/RolesManager/Delete')" class="btn btn-danger">
                                        <i class="fa fa-trash"></i>   删除
                                     </a>
                                </td>
                            </tr>
                        }

                    </tbody>

                </table>
            </div>


        </div>
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
              @Html.PagedListPager(Model,page => Url.Action("List","RolesManager",new{page,search=ViewBag.Search},"https","localhost:7252/Manager"))
            </div>
        </div>



    </div>
</div>

@section Scripts{

    <script src="~/assets/scripts/DeleteData.js"></script>
}