code/sjhy/WebApp/Areas/Manager/Controllers/AdminsManagerController.cs
using Microsoft.AspNetCore.Mvc;
using Entity.ViewModels.Admins;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace WebApp.Areas.Manager.Controllers
{
    [Area("Manager")]
    public class AdminsManagerController : Controller
    {
        private IAdminsService _adminSvc;
        private IRolesService _rolesSvc;
        private IWebHostEnvironment _webEnv;
        public AdminsManagerController(IAdminsService adminSvc, 
                                       IRolesService rolesSvc,
                                       IWebHostEnvironment webEnv)
        {
            _adminSvc = adminSvc;
            _rolesSvc = rolesSvc;
            _webEnv = webEnv;
        }

        [HttpGet]
        public async Task<IActionResult> List(string? search,int page =1)
        {
            search = search ?? "";
            var data = await _adminSvc.GetDataByNameAsync(search);

            var list = new List<AdminsListViewModel>();
            foreach (var item in data)
            {
                list.Add(new AdminsListViewModel
                {
                    Id = item.Id,
                    Name = item.Name,
                    BornDate = item.UpdateTime,
                    Age = item.Age,
                    Gender = item.Gender == 1 ? "男" : "女",
                    Email = item.Email,
                    Tel = item.Tel,
                    Photo = item.Photo,
                    RolesTitle = await GetRolesTitle(item.RolesId),
                    UpdateTime = item.UpdateTime
                });
            }

            IPagedList<AdminsListViewModel> pages = list.ToPagedList(page, PageConfig.PageSize);

            ViewBag.Searcha = search;

            return View(pages);
        }

        [HttpGet]
        public async Task<IActionResult> Add() 
        {
            //1.绑定下拉列表
            //var rolesList = await _rolesSvc.GetAllAsync();
            //SelectList sl = new SelectList(rolesList,"Id","Title");
            //ViewBag.RoleList = sl;
            await Bind(null);
            //SelectList
            return View(new AdminsAddViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Add(AdminsAddViewModel model, IFormFile imgUpload) 
        {
            if (ModelState.IsValid) 
            {
                var img = UploadImage(imgUpload, @"/upload/admins");

                var res = await _adminSvc.AddAdminsAsync(model.Name, model.BornDate, model.Gender, model.Email, model.Tel, img, model.Pwd, model.RolesId);
                if (res > 0)
                    return Redirect("../../../Manager/AdminsManager/List");
            }

            await Bind(null);
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id) 
        {
            var model = await _adminSvc.GetDataByIdAsync(id);
            if(model == null)
                return  Redirect("../../../Manager/AdminsManager/List");

            await Bind(model.RolesId);

            return View(new AdminsEditViewModel 
            {
                Id = model.Id,
                Name = model.Name,
                BornDate = model.BornDate,
                Gender = model.Gender,
                Email = model.Email,
                Tel = model.Tel,
                Photo = model.Photo,
                RolesId = model.RolesId
            
            });
        }
        

        private async Task<string> GetRolesTitle(int id) 
        {
            var data = await _rolesSvc.GetRolesByIdAsync(id);
            return data.Title;
        }

        private async Task Bind(int? id) 
        {
            //1.绑定下拉列表
            var rolesList = await _rolesSvc.GetAllAsync();
            SelectList sl = null;
            if (id == null)
            {
                sl = new SelectList(rolesList, "Id", "Title");
            }
            else 
            {
                sl = new SelectList(rolesList, "Id", "Title",id);
            }
            ViewBag.RoleList = sl;
        }


        private string UploadImage(IFormFile file, string uploadUrl) 
        {
            #region 图片上传
            string img = null;
            if (file == null || string.IsNullOrEmpty(file.FileName))
            {
                img = "default.png";
            }
            else
            {
                //1. 新生成一个图片名称
                Random rand = new Random();
                var newName = DateTime.Now.ToString("yyyyMMdd") + rand.Next(1, 99999)
                            + file.FileName.Substring(file.FileName.LastIndexOf("."));

                //2. 设置要保存到的路径
                string path = _webEnv.WebRootPath + uploadUrl;
                //3.把我们要保存到的路径与图片名称组合在一起形成一个绝对路径
                string url = Path.Combine(path, newName);
                //4. 通过文件流复制这个图片信息到指定的位置
                file.CopyTo(new FileStream(url, FileMode.Create));
                img = newName;
            }
            return img;
            #endregion
        }
    }
}

code/sjhy/WebApp/Areas/Manager/Views/AdminsManager/Add.cshtml
@model Entity.ViewModels.Admins.AdminsAddViewModel
@{
    ViewBag.Title = "新增管理员信息";
}
<div class="panel panel-headline">
    <div class="panel-heading">
        <h3 class="panel-title">新增管理员信息</h3>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <form asp-action="Add" asp-controller="AdminsManager" asp-area="Manager"  method="post" enctype="multipart/form-data">
                    <div class="form-group">
                        <label for="">名称</label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                     <div class="form-group">
                        <label for="">出生日期</label>
                        <input asp-for="BornDate" class="form-control" value="2022-08-10" />
                        <span asp-validation-for="BornDate" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label for="">性别</label>
                        <label class="fancy-radio">
                            <input name="Gender" value="1" type="radio">
                               <span><i></i>男</span>
                        </label>
                         <label class="fancy-radio">
                            <input name="Gender" value="2" type="radio">
                            <span><i></i>女</span>
                         </label>
                        <span asp-validation-for="Gender" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label for="">名称</label>
                        <input asp-for="Email" class="form-control" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label for="">联系电话</label>
                        <input asp-for="Tel" class="form-control" />
                        <span asp-validation-for="Tel" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label for="">上传头像</label>
                        <input type="file" name="imgUpload" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label for="">密码</label>
                        <input asp-for="Pwd" class="form-control" />
                        <span asp-validation-for="Pwd" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label for="">所属身份</label>
                        <select asp-for="RolesId" asp-items="ViewBag.RoleList" class="form-control">
                            <option>请选择</option>
                        </select>
                        <span asp-validation-for="RolesId" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <button class="btn btn-primary">保存</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>  

code/sjhy/WebApp/Areas/Manager/Views/AdminsManager/Edit.cshtml
@model Entity.ViewModels.Admins.AdminsEditViewModel
@{
    ViewBag.Title = "编辑管理员信息";
}
<div class="panel panel-headline">
    <div class="panel-heading">
        <h3 class="panel-title">编辑管理员信息</h3>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <form asp-action="Add" asp-controller="AdminsManager" asp-area="Manager"  method="post" enctype="multipart/form-data">
                    <div class="form-group">
                        <label for="">编号</label>
                        <input asp-for="Id" class="form-control" readonly />
                        <span asp-validation-for="Id" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label for="">名称</label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                     <div class="form-group">
                        <label for="">出生日期</label>
                        <input asp-for="BornDate" class="form-control" value="2022-08-10" />
                        <span asp-validation-for="BornDate" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label for="">性别</label>
                        @if (Model.Gender == 1)
                        {
                                <label class="fancy-radio">
                                <input name="Gender" value="1" type="radio" checked>
                                   <span><i></i>男</span>
                            </label>
                             <label class="fancy-radio">
                                <input name="Gender" value="2" type="radio">
                                <span><i></i>女</span>
                                </label>
                        }
                        else
                        {
                                <label class="fancy-radio">
                                <input name="Gender" value="1" type="radio">
                                   <span><i></i>男</span>
                            </label>
                             <label class="fancy-radio">
                                <input name="Gender" value="2" type="radio" checked>
                                <span><i></i>女</span>
                             </label>

                        }

                        <span asp-validation-for="Gender" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label for="">邮件地址</label>
                        <input asp-for="Email" class="form-control" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label for="">联系电话</label>
                        <input asp-for="Tel" class="form-control" />
                        <span asp-validation-for="Tel" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label for="">上传头像</label>
                        <input type="file" name="imgUpload" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                        <img src="~/upload/admins/@Model.Photo" />


                    </div>
                    <div class="form-group">
                        <label for="">所属身份</label>
                        <select asp-for="RolesId" asp-items="ViewBag.RoleList" class="form-control">
                            <option>请选择</option>
                        </select>
                        <span asp-validation-for="RolesId" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <button class="btn btn-primary">保存</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>  

code/sjhy/WebApp/Areas/Manager/Views/AdminsManager/List.cshtml
@model IPagedList<Entity.ViewModels.Admins.AdminsListViewModel>
@{
    ViewBag.Title = "管理员管理界面";
}

<div class="panel panel-headline">
    <div class="panel-heading">
        <h3 class="panel-title">管理员管理界面</h3>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-5 col-md-offset-1">
                <form asp-action="List" asp-controller="AdminsManager" asp-area="Manager" method="get">
                     <div class="input-group">
                          <input class="form-control" name="search" type="text" value="@ViewBag.Search">
                          <span class="input-group-btn">
                              <button type="submit" class="btn btn-primary" type="button">
                                  <i class="fa fa-search"></i> 搜索</button>
                                  <!-- font-awesome  -->
                          </span>
                     </div>
                </form>
            </div>
            <div class="col-md-3">
                <a asp-action="Add" asp-controller="AdminsManager" asp-area="Manager" class="btn btn-success">
                    <i class="fa fa-plus"></i> 新增管理员信息
                </a>

            </div>

        </div>
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>序号</th>
                            <th>姓名</th>
                            <th>出生日期</th>
                            <th>年龄</th>
                            <th>性别</th>
                            <th>邮件地址</th>
                            <th>联系电话</th>
                            <th>头像</th>
                            <th>身份名称</th>
                            <th>修改时间</th>
                            <th>操作</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.Id</td>
                                <td>@item.Name</td>
                                <td>@item.BornDate</td>
                                <td>@item.Age</td>
                                <td>@item.Gender</td>
                                <td>@item.Email</td>
                                <td>@item.Tel</td>
                                <td>
                                    <img src="~/upload/admins/@item.Photo" />
                                </td>
                                <td>@item.RolesTitle</td>
                                <td>@item.UpdateTime</td>
                                <td>
                                    <a asp-action="Edit" asp-controller="AdminsManager" asp-area="Manager" asp-route-id="@item.Id" class="btn btn-warning">
                                         <i class="fa fa-pencil"></i>   修改
                                    </a>
                                    <a href="javascript:void(0);" onclick="DeleteInfo(@item.Id,'../../../Manager/AdminsManager/Delete')" class="btn btn-danger">
                                        <i class="fa fa-trash"></i>   删除
                                     </a>
                                </td>
                            </tr>
                        }

                    </tbody>

                </table>
            </div>


        </div>
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
              @Html.PagedListPager(Model,page => Url.Action("List","AdminsManager",new{page,search=ViewBag.Search},"https","localhost:7252/Manager"))
            </div>
        </div>



    </div>
</div>

@section Scripts{

    <script src="~/assets/scripts/DeleteData.js"></script>
}