code/sjhy/WebApp/Areas/Manager/Controllers/SystemMenusManagerController.cs
using Microsoft.AspNetCore.Mvc;
using Entity.ViewModels.SystemMenus;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace WebApp.Areas.Manager.Controllers
{
    [Area("Manager")]
    public class SystemMenusManagerController : Controller
    {
        private ISystemMenusService _menusSvc;
        public SystemMenusManagerController(ISystemMenusService menusSvc)
        {
            _menusSvc = menusSvc;
        }

        [HttpGet]
        public async Task<IActionResult> List(string? search,int page= 1)
        {
            search = search ?? string.Empty;
            var data = await _menusSvc.GetDataByTitleAsync(search);

            var list = new List<SystemMenusListViewModel>();

            foreach (var item in data)
            {
                list.Add(new SystemMenusListViewModel
                {
                    Id = item.Id,
                    Title = item.Title,
                    Link = item.Link,
                    Icons = item.Icon,
                    ParentTitle = await getTitle(item.ParentId),
                    UpdateTime = item.UpdateTime.ToString("yyyy-MM-dd")
                });
            }
            IPagedList<SystemMenusListViewModel> pages = list.ToPagedList(page, PageConfig.PageSize);
            ViewBag.Search = search;
            return View(pages);
        }

        [HttpGet]

        public async Task<IActionResult> Add() 
        {
            await Bind(null);
           
            return View(new SystemMenusAddViewModel());
        }
        [HttpPost]
        public async Task<IActionResult> Add(SystemMenusAddViewModel model) 
        {
            if (ModelState.IsValid) 
            {

                int parentId = model.FirstSelect == 0 ? 0 : (int)model.SecondSelect;
                var res = await _menusSvc.AddMenusAsync(model.Title, model.Link, model.Icon, parentId);
                if (res > 0)
                    return Redirect("../../../Manager/SystemMenusManager/List");
            }

            Bind(model.SecondSelect);
            return View(model);
        }


        private async Task Bind(int? parentId) 
        {
            var data = await _menusSvc.GetDataByParentsIdAsync(0);
            SelectList sl = parentId == null ?
                new SelectList(data, "Id", "Title")
                : new SelectList(data, "Id", "Title",parentId);

            ViewBag.SecondMenu = sl;
        }

        private async Task<string> getTitle(int parentId) 
        {
            if (parentId == 0)
                return "一级菜单";
            var data = await _menusSvc.GetDataByIdAsync(parentId);
            return data.Title; 
        }
    }
}

code/sjhy/WebApp/Areas/Manager/Views/SystemMenusManager/Add.cshtml
@model Entity.ViewModels.SystemMenus.SystemMenusAddViewModel
@{
    ViewBag.Title = "新增系统菜单信息";
}

@section Styles{
    
    <style>
        .modal-body>ul>li{
            list-style:none;
            display:inline-block;
            width:24%;
        }
        .modal-body>ul>li>p:first-child{
            font-size:20px;
        }

    </style>

}

<div class="panel panel-headline">
    <div class="panel-heading">
        <h3 class="panel-title">新增系统菜单信息</h3>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <form asp-action="Add" asp-controller="SystemMenusManager" asp-area="Manager"  method="post">
                    <div class="form-group">
                        <label for="">菜单名称</label>
                        <input asp-for="Title" class="form-control" />
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label for="">菜单链接</label>
                        <input asp-for="Link" class="form-control" />
                        <span asp-validation-for="Link" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label for="">菜单图标</label>
                        <input asp-for="Icon" class="form-control" />
                        <button type="button" class="btn btn-success" data-toggle="modal" data-target="#myModal">打开浏览</button>
                        <div id="myModal" class="modal fade" tabindex="-1" aria-labelledby="myModalLabel" role="dialog">
                          <div class="modal-dialog" role="document">
                            <div class="modal-content">
                              <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                <h4 class="modal-title">选择菜单图标</h4>
                              </div>
                              <div class="modal-body">
                                <ul id="chooseIcon">
                                    <li>
                                        <p><i class="fa fa-address-book"></i></p>
                                        <p>fa-address-book</p>
                                    </li>
                                     <li>
                                        <p><i class="fa fa-asterisk"></i></p>
                                        <p>fa-asterisk</p>
                                    </li>
                                     <li>
                                        <p><i class="fa fa-bell"></i></p>
                                        <p>fa-bell</p>
                                    </li>
                                     <li>
                                        <p><i class="fa fa-home"></i></p>
                                        <p>fa-home</p>
                                    </li>
                                     <li>
                                        <p><i class="fa fa-address-book"></i></p>
                                        <p>fa-address-book</p>
                                    </li>
                                     <li>
                                        <p><i class="fa fa-asterisk"></i></p>
                                        <p>fa-asterisk</p>
                                    </li>
                                     <li>
                                        <p><i class="fa fa-bell"></i></p>
                                        <p>fa-bell</p>
                                    </li>
                                     <li>
                                        <p><i class="fa fa-home"></i></p>
                                        <p>fa-home</p>
                                    </li>
                                     <li>
                                        <p><i class="fa fa-address-book"></i></p>
                                        <p>fa-address-book</p>
                                    </li>
                                     <li>
                                        <p><i class="fa fa-asterisk"></i></p>
                                        <p>fa-asterisk</p>
                                    </li>
                                     <li>
                                        <p><i class="fa fa-bell"></i></p>
                                        <p>fa-bell</p>
                                    </li>
                                     <li>
                                        <p><i class="fa fa-home"></i></p>
                                        <p>fa-home</p>
                                    </li>
                                     <li>
                                        <p><i class="fa fa-address-book"></i></p>
                                        <p>fa-address-book</p>
                                    </li>
                                     <li>
                                        <p><i class="fa fa-asterisk"></i></p>
                                        <p>fa-asterisk</p>
                                    </li>
                                     <li>
                                        <p><i class="fa fa-bell"></i></p>
                                        <p>fa-bell</p>
                                    </li>
                                     <li>
                                        <p><i class="fa fa-home"></i></p>
                                        <p>fa-home</p>
                                    </li>
                                     <li>
                                        <p><i class="fa fa-address-book"></i></p>
                                        <p>fa-address-book</p>
                                    </li>
                                     <li>
                                        <p><i class="fa fa-asterisk"></i></p>
                                        <p>fa-asterisk</p>
                                    </li>
                                     <li>
                                        <p><i class="fa fa-bell"></i></p>
                                        <p>fa-bell</p>
                                    </li>
                                     <li>
                                        <p><i class="fa fa-home"></i></p>
                                        <p>fa-home</p>
                                    </li>
                                </ul>
                              </div>
                              <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                              </div>
                            </div><!-- /.modal-content -->
                          </div><!-- /.modal-dialog -->
                        </div><!-- /.modal -->



                        <span asp-validation-for="Icon" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label for="">父级菜单</label>
                        <select id="FirstSelect" name="FirstSelect" class="form-control">
                            <option value="0">一级菜单</option>
                            <option value="1">二级菜单</option>
                        </select>
                        <select asp-for="SecondSelect" asp-items="ViewBag.SecondMenu" class="form-control" style="display:none;">
                            <option value="0">请选择</option>
                        </select>

                       </div>
                    <div class="form-group">
                        <button class="btn btn-primary">保存</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>    
@section Scripts{

        <script>

            $("#FirstSelect").click(function(){
                var v = $(this).val();
                console.log(v);
                if(v == 0){
                    $("#SecondSelect").hide();
                }else
                {
                     $("#SecondSelect").show();
                }
            })

            $("#chooseIcon>li").click(function(){
                
                var el =  $(this).children();
                $("#Icon").val($(el[1]).text());
            
            });


        </script>

}

code/sjhy/WebApp/Areas/Manager/Views/SystemMenusManager/List.cshtml
@model IPagedList<Entity.ViewModels.SystemMenus.SystemMenusListViewModel>
@{
    ViewBag.Title = "系统菜单管理界面";
}

<div class="panel panel-headline">
    <div class="panel-heading">
        <h3 class="panel-title">系统菜单管理界面</h3>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-5 col-md-offset-1">
                <form asp-action="List" asp-controller="SystemMenusManager" asp-area="Manager" method="get">
                     <div class="input-group">
                          <input class="form-control" name="search" type="text" value="@ViewBag.Search">
                          <span class="input-group-btn">
                              <button type="submit" class="btn btn-primary" type="button">
                                  <i class="fa fa-search"></i> 搜索</button>
                                  <!-- font-awesome  -->
                          </span>
                     </div>
                </form>
            </div>
            <div class="col-md-3">
                <a asp-action="Add" asp-controller="SystemMenusManager" asp-area="Manager" class="btn btn-success">
                    <i class="fa fa-plus"></i> 新增系统菜单信息
                </a>

            </div>

        </div>
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>序号</th>
                            <th>系统菜单名称</th>
                            <th>系统菜单链接</th>
                            <th>系统菜单图标</th>
                            <th>父级菜单名称</th>
                            <th>修改时间</th>
                            <th>操作</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.Id</td>
                                <td>@item.Title</td>
                                <td>@item.Link</td>
                                <td>
                                    @if (item.Icons != null)
                                    {
                                        <i class="fa @item.Icons"></i>
                                    }
                                </td>
                                <td>@item.ParentTitle</td>
                                <td>@item.UpdateTime</td>
                                <td>
                                    <a asp-action="Edit" asp-controller="SystemMenusManager" asp-area="Manager" asp-route-id="@item.Id" class="btn btn-warning">
                                         <i class="fa fa-pencil"></i>   修改
                                    </a>
                                    <a href="javascript:void(0);" onclick="DeleteInfo(@item.Id,'../../../Manager/SystemMenusManager/Delete')" class="btn btn-danger">
                                        <i class="fa fa-trash"></i>   删除
                                     </a>
                                </td>
                            </tr>
                        }

                    </tbody>

                </table>
            </div>


        </div>
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
              @Html.PagedListPager(Model,page => Url.Action("List","SystemMenusManager",new{page,search=ViewBag.Search},"https","localhost:7252/Manager"))
            </div>
        </div>



    </div>
</div>

@section Scripts{

    <script src="~/assets/scripts/DeleteData.js"></script>
}